# 1. Use Python image
FROM python:3.11-slim

# 2. Set workdir
WORKDIR /app

# 3. Copy all files
COPY . .

# 4. Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# 5. Expose port
EXPOSE 8000

# 6. Run FastAPI with uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" , "--reload"]
